---
routers:
  - name: R1
    interfaces:
      - name: GigabitEthernet0/0
        ip: 192.168.1.1
        mask: 255.255.255.0
  - name: R2
    interfaces:
      - name: GigabitEthernet0/0
        ip: 192.168.1.2
        mask: 255.255.255.0
ospf_area: 0
